version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable

    steps:
      - checkout

      # Install AWS CLI
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update && sudo apt-get install -y awscli

      # Set AWS credentials as environment variables
      - run:
          name: Set AWS credentials
          command: |
            echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $BASH_ENV
            echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $BASH_ENV
            echo "AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION" >> $BASH_ENV
            export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY

      # Set secret ARN as an environment variable
      - run:
          name: Set secret ARN
          command: |
            echo "SECRET_ARN=$SECRET_ARN" >> $BASH_ENV

      # Debug step to print the secret ARN
      - run:
          name: Debug secret ARN
          command: |
            echo "SECRET_ARN: $SECRET_ARN"

      # Retrieve secret value from Secrets Manager
      - run:
          name: Retrieve secret value
          command: |
            SECRET_VALUE=$(aws secretsmanager get-secret-value --secret-id $SECRET_ARN --query SecretString --output text --region us-east-1)
            SECRET_JSON=$(echo $SECRET_VALUE | jq -r .)
            DB_HOST=$(echo $SECRET_JSON | jq -r .host)
            echo "export DEV_DB_HOST=$DB_HOST" >> $BASH_ENV

      # Debug step to print the secret value
      # - run:
      #     name: Debug secret value
      #     command: |
      #       echo "Secret Value: $SECRET_VALUE"

      # # Extract password from secret value
      # - run:
      #     name: Extract password
      #     command: |
      #       export DB_PASSWORD=$(echo $SECRET_VALUE | jq -r '.password')

      # # Log out the secret value
      # - run:
      #     name: Log secret value
      #     command: |
      #       echo "DB_PASSWORD: $DB_PASSWORD"

      # Set the password as an environment variable
      # - run:
      #     name: Set environment variable
      #     command: |
      #       echo "DB_PASSWORD=$DB_PASSWORD" >> $BASH_ENV

      
